# Generated by Django 5.0.8 on 2024-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_data_reservation_date_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='data',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
