# Generated by Django 5.0.8 on 2024-08-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
    ]
